###############################################################################
# Created by write_sdc
###############################################################################
current_design user_project_wrapper
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name io_clock_PAD -period 10.0000 [get_ports {io_clock_PAD}]
set_clock_transition 0.1500 [get_clocks {io_clock_PAD}]
set_clock_uncertainty 0.2500 io_clock_PAD
set_propagated_clock [get_clocks {io_clock_PAD}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io_0}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io_1}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {io_reset_PAD}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[0]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[10]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[11]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[12]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[13]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[14]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[15]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[1]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[2]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[3]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[4]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[5]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[6]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[7]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[8]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[9]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[0]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[10]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[11]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[12]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[13]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[14]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[15]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[1]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[2]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[3]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[4]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[5]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[6]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[7]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[8]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[9]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io_0}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io_1}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {io_reset_PAD}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[0]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[10]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[11]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[12]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[13]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[14]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[15]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[1]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[2]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[3]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[4]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[5]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[6]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[7]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[8]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {ui_PAD[9]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[0]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[10]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[11]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[12]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[13]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[14]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[15]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[1]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[2]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[3]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[4]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[5]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[6]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[7]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[8]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {uo_PAD[9]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0060 [get_ports {analog_io_0}]
set_load -pin_load 0.0060 [get_ports {analog_io_1}]
set_load -pin_load 0.0060 [get_ports {io_clock_PAD}]
set_load -pin_load 0.0060 [get_ports {io_reset_PAD}]
set_load -pin_load 0.0060 [get_ports {ui_PAD[15]}]
set_load -pin_load 0.0060 [get_ports {ui_PAD[14]}]
set_load -pin_load 0.0060 [get_ports {ui_PAD[13]}]
set_load -pin_load 0.0060 [get_ports {ui_PAD[12]}]
set_load -pin_load 0.0060 [get_ports {ui_PAD[11]}]
set_load -pin_load 0.0060 [get_ports {ui_PAD[10]}]
set_load -pin_load 0.0060 [get_ports {ui_PAD[9]}]
set_load -pin_load 0.0060 [get_ports {ui_PAD[8]}]
set_load -pin_load 0.0060 [get_ports {ui_PAD[7]}]
set_load -pin_load 0.0060 [get_ports {ui_PAD[6]}]
set_load -pin_load 0.0060 [get_ports {ui_PAD[5]}]
set_load -pin_load 0.0060 [get_ports {ui_PAD[4]}]
set_load -pin_load 0.0060 [get_ports {ui_PAD[3]}]
set_load -pin_load 0.0060 [get_ports {ui_PAD[2]}]
set_load -pin_load 0.0060 [get_ports {ui_PAD[1]}]
set_load -pin_load 0.0060 [get_ports {ui_PAD[0]}]
set_load -pin_load 0.0060 [get_ports {uo_PAD[15]}]
set_load -pin_load 0.0060 [get_ports {uo_PAD[14]}]
set_load -pin_load 0.0060 [get_ports {uo_PAD[13]}]
set_load -pin_load 0.0060 [get_ports {uo_PAD[12]}]
set_load -pin_load 0.0060 [get_ports {uo_PAD[11]}]
set_load -pin_load 0.0060 [get_ports {uo_PAD[10]}]
set_load -pin_load 0.0060 [get_ports {uo_PAD[9]}]
set_load -pin_load 0.0060 [get_ports {uo_PAD[8]}]
set_load -pin_load 0.0060 [get_ports {uo_PAD[7]}]
set_load -pin_load 0.0060 [get_ports {uo_PAD[6]}]
set_load -pin_load 0.0060 [get_ports {uo_PAD[5]}]
set_load -pin_load 0.0060 [get_ports {uo_PAD[4]}]
set_load -pin_load 0.0060 [get_ports {uo_PAD[3]}]
set_load -pin_load 0.0060 [get_ports {uo_PAD[2]}]
set_load -pin_load 0.0060 [get_ports {uo_PAD[1]}]
set_load -pin_load 0.0060 [get_ports {uo_PAD[0]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io_0}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io_1}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {io_clock_PAD}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {io_reset_PAD}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_PAD[15]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_PAD[14]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_PAD[13]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_PAD[12]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_PAD[11]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_PAD[10]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_PAD[9]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_PAD[8]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_PAD[7]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_PAD[6]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_PAD[5]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_PAD[4]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_PAD[3]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_PAD[2]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_PAD[1]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_PAD[0]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uo_PAD[15]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uo_PAD[14]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uo_PAD[13]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uo_PAD[12]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uo_PAD[11]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uo_PAD[10]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uo_PAD[9]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uo_PAD[8]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uo_PAD[7]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uo_PAD[6]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uo_PAD[5]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uo_PAD[4]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uo_PAD[3]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uo_PAD[2]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uo_PAD[1]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uo_PAD[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_fanout 10.0000 [current_design]
